version: "3"
services:
  frontend:
    build: ./frontend
    container_name: "code-war-frontend"
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
  api:
    build: ./backend
    container_name: "code-war-api"
    # restart: always
    volumes:
      - ./backend:/usr/src/service
      - ./backend/images:/usr/src/service/images
      - /usr/src/service/node_modules
    working_dir: /usr/src/service
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:5432
  nginx:
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/codewar.access.log:/etc/nginx/log/codewar.access.log
    depends_on:
      - frontend
      - api
  db:
    build: ./postgres
    container_name: "code-war-db"
    # restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=vG8NeGHf92aV6yQCXHYuCUYuZGGX3KWXDHUxDSubUuTtMKMKUMVzYPZpWyYzjGnZXnmCRJfaqwmrD6GMmjSGweYU5xA57cEZNUa42dSrkcRB3FAe2XKr2NYyrHMh4gA5LnqXyxmkx9ZmJQL78LkvZu2DNqwPueRPCTdFmaZHjsJQHgg9PGeFRLf4M5HsCqeYFAj3AvzmTVZN6WSA9YtKUh9kMZ2pjr9hvaSLqfJxjRYJtUV2fYdAEWK6J6kPXd8RDfxzF7U6ctZVeRQYmY3p5J86ZpUa7PHACKSG4UPQBSewGSE6Y8XrTjTz8n5S6zatB2jKaPvgq9TTdnTW2eLArSLLDUYv6WQfFASv7UgFDkPCer9xt7wLLeDeRrL2WNr6uHmcWGfGs8peMDHfS5vLcVJH2rShHjfzrspbQSr9SPmNGRZ2jdXvxdpz3kuuvQ4PfNnt2uYxjsRUpGM6rGxakxbQHK8LmueG9pTpxhUgNLmLL9RQwg2jW8CZtd8VHkbc
      - POSTGRES_USER=codewar
