name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_USER: codewar
      DB_HOST: db
      DB_NAME: codewar
      DB_PASS: vG8NeGHf92aV6yQCXHYuCUYuZGGX3KWXDHUx
      DB_PORT: 5432
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: list all files
        run: ls -lah
      - name: docker compose build
        run: docker-compose up -d

      - name: check docker container
        run: docker ps -a

      - name: unit testing api
        run: docker exec code-war-api npm run test
